FROM node:20-alpine AS base

# Builder stage
FROM base AS builder
# Set working directory
WORKDIR /app
RUN npm install -g turbo
COPY . .
RUN turbo prune @sellzy/worker --docker

# Installer stage
FROM base AS installer
WORKDIR /app

# Ensure we do not run in production mode during install so devDependencies are kept for workspace linking
ENV NODE_ENV=development

# Copy the pruned lockfile and package.json files
COPY --from=builder /app/out/json/ .
RUN npm install

# Build the project
COPY --from=builder /app/out/full/ .
RUN npx turbo run build --filter=@sellzy/worker

# Final runner stage (Optional, but good for reducing image size)
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production

# Copy the built app
COPY --from=installer /app .

CMD ["sh", "-c", "npm run start --workspace=@sellzy/worker"]
