FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
COPY packages ./packages
COPY apps/api ./apps/api
RUN npm install
RUN npm run build --workspace=@sellzy/shared
RUN npm run build --workspace=@sellzy/validation
RUN npm run build --workspace=@sellzy/config
RUN npm run build --workspace=@sellzy/api
EXPOSE 4000
CMD ["npm", "run", "start", "--workspace=@sellzy/api"]
