FROM node:20-alpine AS base

# Builder stage
FROM base AS builder
# Set working directory
WORKDIR /app
RUN npm install -g turbo
COPY . .
RUN turbo prune @sellzy/web --docker

# Installer stage
FROM base AS installer
WORKDIR /app
# First install dependencies (as they change less often)
# Copy the pruned lockfile and package.json files
COPY --from=builder /app/out/json/ .
RUN npm install

# Build the project
COPY --from=builder /app/out/full/ .
RUN npx turbo run build --filter=@sellzy/web

EXPOSE 3000
CMD ["npm", "run", "start", "--workspace=@sellzy/web"]
