FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
COPY packages ./packages
COPY apps/web ./apps/web
RUN npm install
RUN npm run build --workspace=@sellzy/web
EXPOSE 3000
CMD ["npm", "run", "start", "--workspace=@sellzy/web"]
