import mongoose, { Document, Schema } from 'mongoose';

export interface IThemeSection {
  id: string; // Unique instance ID generated by the builder
  type: string; // e.g., 'hero', 'featured-products'
  order: number;
  data: Record<string, any>; // CMS payload (text, image URLs, product IDs)
}

export interface IThemeConfigData {
  header: Record<string, any>;
  footer: Record<string, any>;
  pages: {
    [pageSlug: string]: {
      sections: IThemeSection[];
      metadata: Record<string, any>;
    }
  };
  globalSettings: {
    colors?: Record<string, string>;
    typography?: Record<string, string>;
    [key: string]: any;
  };
}

export interface IThemeConfigurationDocument extends Document {
  tenantId: string;
  themeId: string; // The ID from the Theme Registry (e.g., 'moduva', 'lusion')
  isPublished: boolean; // Is this theme currently live for this tenant?
  draftData: IThemeConfigData; // What the admin is currently editing
  publishedData: IThemeConfigData; // What the live storefront actually serves
  createdAt: Date;
  updatedAt: Date;
}

const themeSectionSchema = new Schema<IThemeSection>({
  id: { type: String, required: true },
  type: { type: String, required: true },
  order: { type: Number, required: true, default: 0 },
  data: { type: Object, default: {} },
}, { _id: false });

const themeConfigDataSchema = new Schema<IThemeConfigData>({
  header: { type: Object, default: {} },
  footer: { type: Object, default: {} },
  pages: { type: Object, default: {} },
  globalSettings: { type: Object, default: {} },
}, { _id: false });

const themeConfigurationSchema = new Schema<IThemeConfigurationDocument>({
  tenantId: { type: String, required: true, index: true },
  themeId: { type: String, required: true, index: true },
  isPublished: { type: Boolean, required: true, default: false },
  draftData: { type: themeConfigDataSchema, default: () => ({ header: {}, footer: {}, pages: {}, globalSettings: {} }) },
  publishedData: { type: themeConfigDataSchema, default: () => ({ header: {}, footer: {}, pages: {}, globalSettings: {} }) },
}, {
  timestamps: true
});

// Ensure a tenant can only have ONE configuration per theme ID
themeConfigurationSchema.index({ tenantId: 1, themeId: 1 }, { unique: true });

export const ThemeConfigurationModel = mongoose.model<IThemeConfigurationDocument>('ThemeConfiguration', themeConfigurationSchema);
